### ISSUE TITLE
Subfolders doesn't work

### ISSUE THREAD

**Issue by simPod** [brabijan/images#22]
I have tried to use this macro: `{img authors/1/profile.jpg, '500x500', exact}` although it doesn't generate the image. If I use `{img authors/profile.jpg, '500x500', exact}` it works. Any ideas?

**Comment by PavelJurasek** [comment]
Problem would be [here](https://github.com/brabijan/images/blob/master/src/Brabijan/Images/Macros/Helpers.php#L21). It expects exactly 2 parts.

**Comment by simPod** [comment]
Ah, thanks. Gonna fork it

**Comment by PavelJurasek** [comment]
There might be even bigger trouble. If you first store ```{var $img = 'authors/1/profile.jpg'}``` (expecting subfolders are fixed) and then try ```{img $img}```, it won't find correct namespace. That's because splitting into namespace and filename is done with tokens.

**Comment by PavelJurasek** [comment]
Try [this branch](https://github.com/PavelJurasek/images/tree/patch-1), please.

**Comment by simPod** [comment]
Thanks, will try it. How do you deal with `Nette\Image` or do you use older nette version? I have to change all of them to `Nette\Utils\Image`

**Comment by simPod** [comment]
I had little time to test it but in `$originalFile = $this->assetsDir . "/" . $this->namespace . $this->originalPrefix . "/" . $image;` `$this->namespace` variable is empty and therefore the original image cannot be found.

**Comment by PavelJurasek** [comment]
Fixing ```Nette\Image``` -> ```Nette\Utils\Image``` should be solved by separate commit.

**Comment by PavelJurasek** [comment]
Force pushed to my branch, it should work now. I tried it myself but feel free to confirm.

**Comment by simPod** [comment]
Do you mean `patch-1`? I tried it but there's still `$this->namespace` variable empty.

I saw other patches in your repo, do you plan on merging them into one branch?

**Comment by PavelJurasek** [comment]
Yes, patch-1. Try it with manual deletion of cached templates that use the macro, please. Maybe it just didn't invalidate automatically.

**Comment by simPod** [comment]
That was it, it's working now.

Another problem is that it doesn't work well with variables (but it's better than before when it wasn't working with them almost at all)
`{img 'profiles/'$profile->id'/profile.jpg',`
makes `$_imagePipe->request('profiles.'/'.'$profile->id'.'/'.profile.jpg'...)`, throws Parse error

This is fine `{img 'profiles'/$profile->id/'profile.jpg'`

It's nothing critical, just saying. Thanks :+1:

**Comment by PavelJurasek** [comment]
You probably don't need to use apostrophes at all.

**Comment by simPod** [comment]
I tried it without them but it strips dots between file name and file extension for example

**Comment by brabijan** [comment]
It should work now - #28
