### ISSUE TITLE
Nefunkční příznak fit

### ISSUE THREAD

**Issue by k4reln** [brabijan/images#37]
Pokud použiji příznak fit, tak se mi pokaždé obrázek ořízne (použije se crop). Po bližším zkoumání se chyba nachází  v souboru src/Brabijan/Images/ImagePipe.php na řádku 205, viz commit ec9d33a5d74a2288cfc2eea79dfa0fc13a7354dc.

Pokud změním porovnávání z $flags == "crop" na $flags === "crop", tak je vše v pořádku. Je to způsobeno tím, že pro PHP je 0 == "retezec" vždy TRUE a konstanta FIT je 0.

**Comment by brabijan** [comment]
wow, díky :)

**Comment by k4reln** [comment]
Není zač, já díky za rychlou opravu ;-)
