### ISSUE TITLE
new tag for version comaptible with nette 2.4

### ISSUE THREAD

**Issue by chemix** [brabijan/images#42]
I use tag 1.0 but it's not commpatible with nette 2.4

version 2.0.0 ?

**Comment by brabijan** [comment]
I don't have time for that at this moment, can you prepare PR? I'm gonna tag it later

**Comment by chemix** [comment]
I think it's only about git tag 2.0.0 ? Or not?

**Comment by chemix** [comment]
relased 2.0.0
